{{- if .Values.clickhouse.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    app: kubesec-clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesec-clickhouse
  template:
    metadata:
      labels:
        app: kubesec-clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.8
          ports:
            - containerPort: 8123 # HTTP
            - containerPort: 9000 # Native
          env:
             # Allow empty password for Alpha
            - name: CLICKHOUSE_DB
              value: kubesec
          volumeMounts:
            #- name: storage
            #  mountPath: /var/lib/clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clickhouse
spec:
  ports:
    - port: 8123
      name: http
      targetPort: 8123
    - port: 9000
      name: native
      targetPort: 9000
  selector:
    app: kubesec-clickhouse
{{- end }}
