apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: kubesec-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: kubesec-server
