apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: kubesec-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kubesec-server
