export const mockWorkloads = [
  {
    id: "1",
    name: "nginx-ingress",
    namespace: "ingress-nginx",
    kind: "Deployment",
    status: "enforcing",
    trainingProgress: 100,
    templateHash: "7f8d9a2b",
    secure: true,
    dryRun: false,
    lastSync: "2025-12-19T12:00:00Z",
    replicas: 3,
    policyVersion: "v18",
  },
  {
    id: "2",
    name: "payment-api",
    namespace: "prod",
    kind: "Deployment",
    status: "training",
    trainingProgress: 65,
    templateHash: "a1b2c3d4",
    secure: true,
    dryRun: true,
    lastSync: "2025-12-19T13:10:00Z",
    replicas: 6,
    policyVersion: "v7",
  },
  {
    id: "3",
    name: "redis-master",
    namespace: "prod",
    kind: "StatefulSet",
    status: "enforcing",
    trainingProgress: 100,
    templateHash: "e5f6g7h8",
    secure: true,
    dryRun: false,
    lastSync: "2025-12-19T11:45:00Z",
    replicas: 1,
    policyVersion: "v22",
  },
]

export const mockEvents = [
  {
    id: "e1",
    timestamp: "2025-12-19T13:15:02Z",
    podName: "payment-api-6f8d9a2b-xcvbn",
    namespace: "prod",
    workload: "payment-api",
    syscall: "openat",
    argument: "/etc/passwd",
    action: "blocked",
    comm: "cat",
    risk: "high",
  },
  {
    id: "e2",
    timestamp: "2025-12-19T13:15:10Z",
    podName: "payment-api-6f8d9a2b-xcvbn",
    namespace: "prod",
    workload: "payment-api",
    syscall: "connect",
    argument: "1.2.3.4:443",
    action: "learned",
    comm: "node",
    risk: "low",
  },
  {
    id: "e3",
    timestamp: "2025-12-19T13:15:15Z",
    podName: "nginx-ingress-7f8d9a2b-asdfg",
    namespace: "ingress-nginx",
    workload: "nginx-ingress",
    syscall: "execve",
    argument: "/usr/bin/python3",
    action: "blocked",
    comm: "sh",
    risk: "medium",
  },
  {
    id: "e4",
    timestamp: "2025-12-19T13:16:01Z",
    podName: "redis-master-0",
    namespace: "prod",
    workload: "redis-master",
    syscall: "openat",
    argument: "/proc/kcore",
    action: "blocked",
    comm: "cat",
    risk: "high",
  },
  {
    id: "e5",
    timestamp: "2025-12-19T13:16:07Z",
    podName: "nginx-ingress-7f8d9a2b-asdfg",
    namespace: "ingress-nginx",
    workload: "nginx-ingress",
    syscall: "connect",
    argument: "10.0.3.19:53",
    action: "allowed",
    comm: "nginx",
    risk: "low",
  },
]

export const mockAuditLogs = [
  {
    id: "a1",
    timestamp: "2025-12-19T10:30:00Z",
    user: "admin@kubesec.io",
    workload: "Deployment/prod/payment-api",
    action: "ALLOW",
    syscall: "openat",
    argument: "/var/run/secrets/kubernetes.io/serviceaccount/token",
    reason: "Required for K8s API communication",
  },
  {
    id: "a2",
    timestamp: "2025-12-19T11:15:00Z",
    user: "soc-analyst-1",
    workload: "Deployment/prod/payment-api",
    action: "BLOCK",
    syscall: "execve",
    argument: "/usr/bin/nc",
    reason: "Unauthorized tool detected",
  },
  {
    id: "a3",
    timestamp: "2025-12-19T12:40:00Z",
    user: "soc-analyst-2",
    workload: "Deployment/ingress-nginx/nginx-ingress",
    action: "LEARN",
    syscall: "connect",
    argument: "10.0.3.19:53",
    reason: "DNS resolver call observed during baseline",
  },
]

export const mockPolicyBaseline = [
  {
    id: "l1",
    createdAt: "2025-12-19T13:15:03Z",
    workload: "payment-api",
    namespace: "prod",
    syscall: "openat",
    argument: "/etc/passwd",
    comm: "cat",
    analyst: "soc-analyst-1",
    status: "needs-review",
    notes: "Looks like a debug container or unexpected shell usage.",
    recommended: "block",
  },
  {
    id: "l2",
    createdAt: "2025-12-19T13:15:16Z",
    workload: "nginx-ingress",
    namespace: "ingress-nginx",
    syscall: "execve",
    argument: "/usr/bin/python3",
    comm: "sh",
    analyst: "soc-analyst-2",
    status: "needs-review",
    notes: "Could be a sidecar doing cert renewals; verify image hash.",
    recommended: "learn",
  },
  {
    id: "l3",
    createdAt: "2025-12-19T12:39:59Z",
    workload: "payment-api",
    namespace: "prod",
    syscall: "connect",
    argument: "10.0.3.19:53",
    comm: "node",
    analyst: "soc-analyst-2",
    status: "approved",
    notes: "Name resolution required.",
    recommended: "learn",
  },
  {
    id: "l4",
    createdAt: "2025-12-19T13:16:02Z",
    workload: "redis-master",
    namespace: "prod",
    syscall: "openat",
    argument: "/proc/kcore",
    comm: "cat",
    analyst: "soc-analyst-1",
    status: "needs-review",
    notes: "Potential malicious attempt to read kernel memory.",
    recommended: "block",
  },
]

// 60 samples (to render 60 bars in the blocked chart)
// NOTE: each sample has blocked >= 1 so every bar is visible.
export const mockTimeseries = [
  { t: "13:00", blocked: 9, learned: 2, allowed: 14 },
  { t: "13:01", blocked: 1, learned: 0, allowed: 16 },
  { t: "13:02", blocked: 1, learned: 0, allowed: 18 },
  { t: "13:03", blocked: 1, learned: 0, allowed: 20 },
  { t: "13:04", blocked: 1, learned: 1, allowed: 18 },
  { t: "13:05", blocked: 2, learned: 0, allowed: 20 },
  { t: "13:06", blocked: 1, learned: 0, allowed: 22 },
  { t: "13:07", blocked: 3, learned: 0, allowed: 24 },
  { t: "13:08", blocked: 1, learned: 2, allowed: 22 },
  { t: "13:09", blocked: 1, learned: 0, allowed: 15 },
  { t: "13:10", blocked: 2, learned: 0, allowed: 17 },
  { t: "13:11", blocked: 6, learned: 0, allowed: 19 },
  { t: "13:12", blocked: 1, learned: 1, allowed: 17 },
  { t: "13:13", blocked: 1, learned: 0, allowed: 19 },
  { t: "13:14", blocked: 3, learned: 0, allowed: 21 },
  { t: "13:15", blocked: 2, learned: 0, allowed: 23 },
  { t: "13:16", blocked: 1, learned: 2, allowed: 21 },
  { t: "13:17", blocked: 9, learned: 0, allowed: 23 },
  { t: "13:18", blocked: 1, learned: 0, allowed: 16 },
  { t: "13:19", blocked: 1, learned: 0, allowed: 18 },
  { t: "13:20", blocked: 2, learned: 1, allowed: 16 },
  { t: "13:21", blocked: 3, learned: 0, allowed: 18 },
  { t: "13:22", blocked: 6, learned: 0, allowed: 20 },
  { t: "13:23", blocked: 1, learned: 0, allowed: 22 },
  { t: "13:24", blocked: 1, learned: 2, allowed: 20 },
  { t: "13:25", blocked: 2, learned: 0, allowed: 22 },
  { t: "13:26", blocked: 1, learned: 0, allowed: 24 },
  { t: "13:27", blocked: 1, learned: 0, allowed: 17 },
  { t: "13:28", blocked: 3, learned: 1, allowed: 15 },
  { t: "13:29", blocked: 1, learned: 0, allowed: 17 },
  { t: "13:30", blocked: 2, learned: 0, allowed: 19 },
  { t: "13:31", blocked: 1, learned: 0, allowed: 21 },
  { t: "13:32", blocked: 1, learned: 2, allowed: 19 },
  { t: "13:33", blocked: 6, learned: 0, allowed: 21 },
  { t: "13:34", blocked: 9, learned: 0, allowed: 23 },
  { t: "13:35", blocked: 3, learned: 0, allowed: 25 },
  { t: "13:36", blocked: 1, learned: 1, allowed: 14 },
  { t: "13:37", blocked: 1, learned: 0, allowed: 16 },
  { t: "13:38", blocked: 1, learned: 0, allowed: 18 },
  { t: "13:39", blocked: 1, learned: 0, allowed: 20 },
  { t: "13:40", blocked: 2, learned: 2, allowed: 18 },
  { t: "13:41", blocked: 1, learned: 0, allowed: 20 },
  { t: "13:42", blocked: 3, learned: 0, allowed: 22 },
  { t: "13:43", blocked: 1, learned: 0, allowed: 24 },
  { t: "13:44", blocked: 6, learned: 1, allowed: 22 },
  { t: "13:45", blocked: 2, learned: 0, allowed: 15 },
  { t: "13:46", blocked: 1, learned: 0, allowed: 17 },
  { t: "13:47", blocked: 1, learned: 0, allowed: 19 },
  { t: "13:48", blocked: 1, learned: 2, allowed: 17 },
  { t: "13:49", blocked: 3, learned: 0, allowed: 19 },
  { t: "13:50", blocked: 2, learned: 0, allowed: 21 },
  { t: "13:51", blocked: 9, learned: 0, allowed: 23 },
  { t: "13:52", blocked: 1, learned: 1, allowed: 21 },
  { t: "13:53", blocked: 1, learned: 0, allowed: 23 },
  { t: "13:54", blocked: 1, learned: 0, allowed: 16 },
  { t: "13:55", blocked: 6, learned: 0, allowed: 18 },
  { t: "13:56", blocked: 3, learned: 2, allowed: 16 },
  { t: "13:57", blocked: 1, learned: 0, allowed: 18 },
  { t: "13:58", blocked: 1, learned: 0, allowed: 20 },
  { t: "13:59", blocked: 1, learned: 0, allowed: 22 },
]
