// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type syscallTracerAllowlistKey struct {
	_         structs.HostLayout
	CgroupId  uint64
	SyscallNr uint32
	ArgStr    [128]int8
	_         [4]byte
}

type syscallTracerKeyT struct {
	_         structs.HostLayout
	CgroupId  uint64
	SyscallNr uint32
	_         [4]byte
}

type syscallTracerPrefixKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	_         [4]byte
	CgroupId  uint64
	SyscallNr uint32
	Path      [128]int8
	_         [4]byte
}

// loadSyscallTracer returns the embedded CollectionSpec for syscallTracer.
func loadSyscallTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load syscallTracer: %w", err)
	}

	return spec, err
}

// loadSyscallTracerObjects loads syscallTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*syscallTracerObjects
//	*syscallTracerPrograms
//	*syscallTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSyscallTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSyscallTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// syscallTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTracerSpecs struct {
	syscallTracerProgramSpecs
	syscallTracerMapSpecs
	syscallTracerVariableSpecs
}

// syscallTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTracerProgramSpecs struct {
	SysEnter *ebpf.ProgramSpec `ebpf:"sys_enter"`
}

// syscallTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTracerMapSpecs struct {
	AkeyScratch     *ebpf.MapSpec `ebpf:"akey_scratch"`
	AllowedPrefixes *ebpf.MapSpec `ebpf:"allowed_prefixes"`
	AllowedSyscalls *ebpf.MapSpec `ebpf:"allowed_syscalls"`
	BlockedSyscalls *ebpf.MapSpec `ebpf:"blocked_syscalls"`
	EnforcementMode *ebpf.MapSpec `ebpf:"enforcement_mode"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	PkeyScratch     *ebpf.MapSpec `ebpf:"pkey_scratch"`
	TargetCgroups   *ebpf.MapSpec `ebpf:"target_cgroups"`
}

// syscallTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type syscallTracerVariableSpecs struct {
}

// syscallTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTracerObjects struct {
	syscallTracerPrograms
	syscallTracerMaps
	syscallTracerVariables
}

func (o *syscallTracerObjects) Close() error {
	return _SyscallTracerClose(
		&o.syscallTracerPrograms,
		&o.syscallTracerMaps,
	)
}

// syscallTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTracerMaps struct {
	AkeyScratch     *ebpf.Map `ebpf:"akey_scratch"`
	AllowedPrefixes *ebpf.Map `ebpf:"allowed_prefixes"`
	AllowedSyscalls *ebpf.Map `ebpf:"allowed_syscalls"`
	BlockedSyscalls *ebpf.Map `ebpf:"blocked_syscalls"`
	EnforcementMode *ebpf.Map `ebpf:"enforcement_mode"`
	Events          *ebpf.Map `ebpf:"events"`
	PkeyScratch     *ebpf.Map `ebpf:"pkey_scratch"`
	TargetCgroups   *ebpf.Map `ebpf:"target_cgroups"`
}

func (m *syscallTracerMaps) Close() error {
	return _SyscallTracerClose(
		m.AkeyScratch,
		m.AllowedPrefixes,
		m.AllowedSyscalls,
		m.BlockedSyscalls,
		m.EnforcementMode,
		m.Events,
		m.PkeyScratch,
		m.TargetCgroups,
	)
}

// syscallTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTracerVariables struct {
}

// syscallTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSyscallTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type syscallTracerPrograms struct {
	SysEnter *ebpf.Program `ebpf:"sys_enter"`
}

func (p *syscallTracerPrograms) Close() error {
	return _SyscallTracerClose(
		p.SysEnter,
	)
}

func _SyscallTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscalltracer_arm64_bpfel.o
var _SyscallTracerBytes []byte
